FROM golang:1.24 AS builder

   WORKDIR /app
   COPY go.mod go.sum ./
   RUN go mod download
   COPY . .
   RUN CGO_ENABLED=0 GOOS=linux go build -o app .


   FROM alpine:3.21
   WORKDIR /root/
   COPY --from=builder /app/app .
   CMD ["./app"]